# Generated by Django 6.0 on 2026-04-24 21:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('resumen', models.TextField(max_length=300)),
                ('contenido', models.TextField()),
                ('icono', models.CharField(default='fa-solid fa-code', help_text='Clase de FontAwesome (ej. fa-brands fa-python)', max_length=50)),
                ('color_tema', models.CharField(default='emerald', help_text='emerald, cyan, blue, purple, etc.', max_length=50)),
                ('autor', models.CharField(default='Equipo Perseus', max_length=100)),
                ('tiempo_lectura', models.IntegerField(default=5, help_text='Minutos de lectura')),
                ('destacado', models.BooleanField(default=False)),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
            options={
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
