# Generated by Django 6.0 on 2026-04-24 22:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoria_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='icono',
        ),
        migrations.AddField(
            model_name='post',
            name='imagen_portada',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen'),
        ),
    ]
